import { TerrainSystem } from "./TerrainSystem.js";


// ============================================================
// FAR TERRAIN SYSTEM (quadtree)
// ============================================================
//
// Draws terrain from the player out to `maxDistance` using a
// quadtree of nodes. Every node is a normal TerrainSystem
// (33x33 vertices, generated by the existing worker pool), but
// node sizes double with distance: 128, 256, 512, 1024.
//
// Nodes split when the player is closer than splitFactor * size,
// so the vertex spacing grows with distance (size / 32).
//
// Alignment: nodes are aligned to the chunk lattice. A node of
// size S at index (i, j) spans
//     x in [S*i - chunkSize/2, S*(i+1) - chunkSize/2]
// so its edges coincide with the edges of your 64-unit chunks.
//
// NEAR CHUNKS
//   The far quadtree covers the whole area, including the area
//   under your near chunks. Far nodes are drawn AFTER everything
//   else (renderOrder 1) with a depth bias that pushes them away,
//   so the near chunks always win where both exist. That means a
//   near chunk that is still loading (or just unloaded) never
//   leaves a hole.
//
// NO HOLES WHILE LOADING
//   Nodes load coarse-first. A node that is not ready yet is
//   replaced by its ready children (when merging) or by its
//   ready parent (when splitting), so the displayed set is
//   always an exact partition without overlaps.
//
// FAR WATER (optional)
//   Pass a WaterSystem instance as `water`. Each node registers
//   its water mesh there, shown and hidden together with the node.
// ============================================================


const CHILDREN = [[0, 0], [1, 0], [0, 1], [1, 1]];


export class FarTerrainSystem {

    constructor(options = {}) {

        const cm = options.chunkManager ?? null;

        this.scene = options.scene ?? cm?.scene;
        this.pool = options.terrainWorkerPool ?? cm?.terrainWorkerPool;
        this.surfaceSystem = options.surfaceSystem ?? cm?.surfaceSystem ?? null;
        this.sun = options.sun ?? cm?.sun ?? null;

        this.world = {
            seed: options.seed ?? cm?.seed ?? 482917,
            baseHeight: options.baseHeight ?? cm?.baseHeight ?? 0.0,
            maxHeight: options.maxHeight ?? cm?.maxHeight ?? 14.2,
            heightScale: options.heightScale ?? cm?.heightScale ?? 6.0
        };

        this.chunkSize = options.chunkSize ?? cm?.chunkSize ?? 64;
        this.nearViewDistance =
            options.nearViewDistance ?? cm?.viewDistance ?? 3;

        // Optional shared instances (recommended with the rewritten TerrainSystem)
        this.worldGenerator = options.worldGenerator ?? null;
        this.propDistributionSystem = options.propDistributionSystem ?? null;

        this.water = options.water ?? null;

        // ---------------- quadtree settings ----------------

        // Smallest and largest node size. Must be multiples of chunkSize.
        this.minSize = options.minNodeSize ?? this.chunkSize * 2;
        this.maxSize = options.maxNodeSize ?? this.minSize * 8;

        // Terrain is drawn out to this distance from the player
        this.maxDistance = options.maxDistance ?? 2500;

        // A node splits when distance < splitFactor * size.
        // Higher = finer terrain further out, but more nodes.
        this.splitFactor = options.splitFactor ?? 2.0;

        this.nodeResolution = options.nodeResolution ?? 32;

        // How many nodes may be generating at once. Keep it low so
        // near chunk jobs are not stuck behind far ones.
        this.maxInFlight = options.maxInFlight ?? 3;

        // Unused nodes are kept this long (seconds) before disposal
        this.retainSeconds = options.retainSeconds ?? 8;

        // Depth bias that pushes far terrain behind near chunks
        this.biasFactor = options.biasFactor ?? 2;
        this.biasUnits = options.biasUnits ?? 32;

        this.maxLevel = Math.max(
            0,
            Math.round(Math.log2(this.maxSize / this.minSize))
        );

        // Chunk edges sit half a chunk away from the origin
        this.offset = this.chunkSize * 0.5;

        // Re-select when the player moved this far
        this.reselectDistance = this.minSize / 16;

        // ---------------- material ----------------

        this.ownsMaterial = false;

        this.material = options.material ?? null;

        if (!this.material && TerrainSystem.createMaterial) {

            this.material = TerrainSystem.createMaterial();
            this.ownsMaterial = true;
        }

        // ---------------- state ----------------

        this.nodes = new Map();
        this.wanted = [];
        this.roots = [];
        this.splitSet = new Set();
        this.prevSplit = new Set();

        this.time = 0;
        this.timer = 0;
        this.dirty = true;
        this.inFlight = 0;

        this.selX = NaN;
        this.selZ = NaN;

        if (!this.pool) {
            console.error("FarTerrainSystem: no terrainWorkerPool available.");
        }
    }


    // ==================================================
    // HELPERS
    // ==================================================

    nodeKey(level, i, j) {

        return `${level}:${i}:${j}`;
    }


    nodeSize(level) {

        return this.minSize * (1 << level);
    }


    // Distance from the selection point to the node's square
    distanceTo(level, i, j) {

        const size = this.nodeSize(level);

        const minX = size * i - this.offset;
        const minZ = size * j - this.offset;

        const dx = Math.max(minX - this.selX, 0, this.selX - (minX + size));
        const dz = Math.max(minZ - this.selZ, 0, this.selZ - (minZ + size));

        return Math.hypot(dx, dz);
    }


    // ==================================================
    // UPDATE
    // ==================================================
    //
    // Call every frame, after chunkManager.update():
    //   farTerrain.update(delta, playerPosition)
    //

    update(delta, playerPosition) {

        this.time += delta;

        if (!playerPosition) {
            return;
        }

        const px = playerPosition.x;
        const pz = playerPosition.z;

        this.updateWaterExclusion(px, pz);

        this.timer += delta;

        const moved =
            Math.hypot(px - this.selX, pz - this.selZ) > this.reselectDistance;

        if (
            this.dirty ||
            (moved && this.timer > 0.1) ||
            this.timer > 1.0
        ) {

            this.selX = px;
            this.selZ = pz;
            this.timer = 0;

            this.refresh();
        }
    }


    // The far water must not draw inside the near chunk square,
    // where the near WaterSystem already draws water.
    updateWaterExclusion(px, pz) {

        if (!this.water || !this.water.setExclusionRect) {
            return;
        }

        const cx = Math.floor(px / this.chunkSize) * this.chunkSize;
        const cz = Math.floor(pz / this.chunkSize) * this.chunkSize;

        const half = (this.nearViewDistance + 0.5) * this.chunkSize;

        this.water.setExclusionRect(
            cx - half,
            cz - half,
            cx + half,
            cz + half
        );
    }


    refresh() {

        this.prevSplit = this.splitSet;
        this.splitSet = new Set();

        this.wanted.length = 0;
        this.roots.length = 0;

        this.select();

        // Coarse first (fallbacks), then nearest first
        this.wanted.sort((a, b) =>
            b.level - a.level || a.dist - b.dist
        );

        this.requestNodes();
        this.resolveDisplay();
        this.disposeStale();

        this.dirty = false;
    }


    // ==================================================
    // SELECTION
    // ==================================================

    select() {

        const size = this.maxSize;
        const R = this.maxDistance;

        const iMin = Math.floor((this.selX - R + this.offset) / size);
        const iMax = Math.floor((this.selX + R + this.offset) / size);
        const jMin = Math.floor((this.selZ - R + this.offset) / size);
        const jMax = Math.floor((this.selZ + R + this.offset) / size);

        for (let i = iMin; i <= iMax; i++) {
            for (let j = jMin; j <= jMax; j++) {

                if (this.distanceTo(this.maxLevel, i, j) > R) {
                    continue;
                }

                this.roots.push({ level: this.maxLevel, i, j });

                this.visit(this.maxLevel, i, j);
            }
        }
    }


    visit(level, i, j) {

        const dist = this.distanceTo(level, i, j);

        if (dist > this.maxDistance) {
            return;
        }

        const key = this.nodeKey(level, i, j);

        // Every visited node is wanted: leaves for display, and
        // internal nodes as coarse fallbacks while children load.
        this.wanted.push({ level, i, j, key, dist });

        if (level > 0) {

            // Hysteresis: an already split node stays split a bit longer
            const factor = this.prevSplit.has(key)
                ? this.splitFactor * 1.15
                : this.splitFactor;

            if (dist < factor * this.nodeSize(level)) {

                this.splitSet.add(key);

                for (const [cx, cz] of CHILDREN) {
                    this.visit(level - 1, i * 2 + cx, j * 2 + cz);
                }
            }
        }
    }


    // ==================================================
    // NODE CREATION
    // ==================================================

    requestNodes() {

        for (const w of this.wanted) {

            const node = this.nodes.get(w.key);

            if (node) {
                node.lastUsed = this.time;
                continue;
            }

            if (this.inFlight >= this.maxInFlight) {
                continue;
            }

            this.createNode(w.level, w.i, w.j);
        }
    }


    createNode(level, i, j) {

        const size = this.nodeSize(level);

        const centerX = size * (i + 0.5) - this.offset;
        const centerZ = size * (j + 0.5) - this.offset;

        const key = this.nodeKey(level, i, j);

        const node = {
            key,
            level,
            i,
            j,
            size,
            centerX,
            centerZ,
            terrain: null,
            loading: true,
            ready: false,
            visible: false,
            disposed: false,
            lastUsed: this.time,
            created: performance.now(),
            waterX: `F${level}_${i}`,
            waterZ: j
        };

        this.nodes.set(key, node);
        this.inFlight++;

        node.terrain = new TerrainSystem({

            scene: this.scene,
            sun: this.sun,

            size,
            resolution: this.nodeResolution,

            baseHeight: this.world.baseHeight,
            maxHeight: this.world.maxHeight,
            heightScale: this.world.heightScale,
            seed: this.world.seed,

            worldOffsetX: centerX,
            worldOffsetZ: centerZ,

            surfaceSystem: this.surfaceSystem,
            terrainWorkerPool: this.pool,

            material: this.material,
            worldGenerator: this.worldGenerator,
            propDistributionSystem: this.propDistributionSystem,

            onTerrainReady: (terrain) => this.onNodeReady(node, terrain)
        });
    }


    onNodeReady(node, terrain) {

        if (node.disposed) {
            return;
        }

        node.ready = true;
        node.loading = false;

        this.inFlight = Math.max(0, this.inFlight - 1);

        // Hidden until resolveDisplay() decides to show it
        this.setTerrainVisible(terrain, false);

        // Far terrain: drawn after near geometry, biased away in
        // depth, no shadow lookups.
        const meshes = [terrain.mesh, terrain.skirtMesh];

        for (const mesh of meshes) {

            if (!mesh) {
                continue;
            }

            mesh.renderOrder = 1;
            mesh.receiveShadow = false;
            mesh.castShadow = false;
        }

        const material = terrain.material;

        if (material) {

            material.polygonOffset = true;
            material.polygonOffsetFactor = this.biasFactor;
            material.polygonOffsetUnits = this.biasUnits;
        }

        if (this.water) {

            this.water.registerTerrainChunk({
                x: node.waterX,
                z: node.waterZ,
                terrain
            });

            this.water.setChunkEnabled(node.waterX, node.waterZ, false);
        }

        this.dirty = true;
    }


    setTerrainVisible(terrain, visible) {

        if (terrain.mesh) {
            terrain.mesh.visible = visible;
        }

        if (terrain.skirtMesh) {
            terrain.skirtMesh.visible = visible;
        }
    }


    // ==================================================
    // DISPLAY RESOLUTION
    // ==================================================
    //
    // Builds the set of ready nodes to draw: an exact partition
    // of the wanted area with no overlaps and no holes.
    //

    resolveDisplay() {

        const out = [];

        for (const r of this.roots) {
            this.cover(r.level, r.i, r.j, out);
        }

        const show = new Set(out);

        for (const node of out) {
            node.lastUsed = this.time;
        }

        for (const node of this.nodes.values()) {

            if (!node.ready) {
                continue;
            }

            const visible = show.has(node);

            if (node.visible !== visible) {
                this.setNodeVisible(node, visible);
            }
        }
    }


    setNodeVisible(node, visible) {

        node.visible = visible;

        this.setTerrainVisible(node.terrain, visible);

        if (this.water) {
            this.water.setChunkEnabled(node.waterX, node.waterZ, visible);
        }
    }


    // Pushes ready nodes covering this node's area into `out`.
    // Returns false if the area can't be covered right now.
    cover(level, i, j, out) {

        if (this.distanceTo(level, i, j) > this.maxDistance) {
            return true;    // nothing wanted here
        }

        const key = this.nodeKey(level, i, j);
        const node = this.nodes.get(key);
        const ready = node !== undefined && node.ready;

        // Desired leaf
        if (!this.splitSet.has(key)) {

            if (ready) {
                out.push(node);
                return true;
            }

            // Not ready: keep showing finer nodes that still exist
            return this.coverFromChildren(level, i, j, out);
        }

        // Desired split: use the children if all of them can cover
        const mark = out.length;

        let ok = true;

        for (const [cx, cz] of CHILDREN) {

            if (!this.cover(level - 1, i * 2 + cx, j * 2 + cz, out)) {
                ok = false;
                break;
            }
        }

        if (ok) {
            return true;
        }

        // Otherwise fall back to this (coarser) node
        out.length = mark;

        if (ready) {
            out.push(node);
            return true;
        }

        return false;
    }


    coverFromChildren(level, i, j, out) {

        if (level === 0) {
            return false;
        }

        const mark = out.length;

        for (const [cx, cz] of CHILDREN) {

            const ci = i * 2 + cx;
            const cj = j * 2 + cz;

            if (this.distanceTo(level - 1, ci, cj) > this.maxDistance) {
                continue;
            }

            const child = this.nodes.get(this.nodeKey(level - 1, ci, cj));

            if (child && child.ready) {
                out.push(child);
            } else if (!this.coverFromChildren(level - 1, ci, cj, out)) {
                out.length = mark;
                return false;
            }
        }

        return true;
    }


    // ==================================================
    // CLEANUP
    // ==================================================

    disposeStale() {

        const now = performance.now();

        for (const [key, node] of this.nodes) {

            const age = this.time - node.lastUsed;

            // Generation that never finished (worker error)
            const timedOut = node.loading && now - node.created > 30000;

            if ((age > this.retainSeconds && !node.visible) || timedOut) {

                this.disposeNode(node);
                this.nodes.delete(key);
            }
        }
    }


    disposeNode(node) {

        node.disposed = true;

        if (node.loading) {
            this.inFlight = Math.max(0, this.inFlight - 1);
        }

        if (this.water && node.ready) {
            this.water.unregisterTerrainChunk(node.waterX, node.waterZ);
        }

        if (node.terrain) {
            node.terrain.dispose();
        }
    }


    // ==================================================
    // DEBUG
    // ==================================================

    // Shows the node structure. Call setWireframe(false) to restore.
    setWireframe(enabled) {

        if (this.material) {

            this.material.wireframe = enabled;
            return;
        }

        for (const node of this.nodes.values()) {

            if (node.terrain && node.terrain.material) {
                node.terrain.material.wireframe = enabled;
            }
        }
    }


    getStats() {

        let ready = 0;
        let visible = 0;
        let loading = 0;

        const bySize = {};

        for (const node of this.nodes.values()) {

            if (node.ready) ready++;
            if (node.loading) loading++;

            if (node.visible) {

                visible++;
                bySize[node.size] = (bySize[node.size] ?? 0) + 1;
            }
        }

        return {
            nodes: this.nodes.size,
            ready,
            loading,
            visible,
            visibleBySize: bySize
        };
    }


    // ==================================================
    // DISPOSE
    // ==================================================

    dispose() {

        for (const node of this.nodes.values()) {
            this.disposeNode(node);
        }

        this.nodes.clear();

        if (this.ownsMaterial && this.material) {

            this.material.dispose();
            this.material = null;
        }
    }
}